config/routes.rb
Rails.application.routes.draw do
  root 'trails#index'

  resources :trails, only: [:index, :show, :new, :create]
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :trails do
    resources :reviews
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show]
      resources :trails, only: [:index, :show]
      resources :likes, only: [:create, :index]
    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
  <title>Ruby On Trails</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Ruby On Trails</a></h1>
      </li>
      <li class="toggle-topbar menu-icon">
        <a href="#"><span>menu</span></a>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <ul class="dropdown">
        </ul>
          <%- if current_user -%>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Add New Trail', new_trail_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Admin Section", users_path %></li>
          <% end %>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li class="active"><%= link_to 'Sign In', new_user_session_path %></li>
          <%- end -%>
        </ul>
    </section>
  </nav>
</div>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

    <div class="row">
      <div class="container">
        <%= yield %>
      </div>
    </div>

  <%= javascript_include_tag 'application' %>

  <%= javascript_pack_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>